// Expo config plugin: fix fmt compilation under Xcode 26 / newer Clang.
//
// React Native 0.79.x pins fmt 11.0.2, whose fmt/base.h unconditionally
// #defines FMT_CONSTEVAL as `consteval` when the compiler advertises support
// (__cpp_consteval). Xcode 26's Clang trips that branch, and its stricter
// consteval evaluation then rejects fmt's compile-time format-string checks:
//
//   error: call to consteval function
//   'fmt::basic_format_string<...>::basic_format_string<...>'
//   is not a constant expression   (ios/Pods/fmt/include/fmt/format-inl.h)
//
// Because base.h has no `#ifndef FMT_CONSTEVAL` guard, a `-DFMT_CONSTEVAL=`
// build flag can't override it. The reliable fix is to patch base.h so the
// empty (runtime) definition is used instead — format-string checks then run
// at runtime, which is functionally fine.
//
// `ios/` is gitignored (regenerated by `expo prebuild`), so the patch must be
// re-applied on every prebuild. This plugin injects the patch into the
// generated Podfile's post_install hook, which runs at `pod install` time —
// after the fmt pod source is present but before it is compiled.
//
// Remove this plugin once the project moves to a React Native / fmt version
// that compiles cleanly under Xcode 26 (e.g. a newer Expo SDK).

const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const ANCHOR = "post_install do |installer|";
const MARKER = "withFmtXcode26Fix";

const RUBY_SNIPPET = `
    # [withFmtXcode26Fix] Force the empty (runtime) FMT_CONSTEVAL definition so
    # fmt 11.0.2 compiles under Xcode 26 / newer Clang. See plugins/withFmtXcode26Fix.js.
    fmt_base = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      fmt_text = File.read(fmt_base)
      fmt_patched = fmt_text.gsub("#if FMT_USE_CONSTEVAL\\n#  define FMT_CONSTEVAL consteval",
                                  "#if 0 // patched by withFmtXcode26Fix for Xcode 26\\n#  define FMT_CONSTEVAL consteval")
      if fmt_patched != fmt_text
        File.chmod(0644, fmt_base)
        File.write(fmt_base, fmt_patched)
        Pod::UI.puts "[withFmtXcode26Fix] Disabled FMT_CONSTEVAL in fmt/base.h for Xcode 26 compatibility" if defined?(Pod::UI)
      end
    end
`;

const withFmtXcode26Fix = (config) =>
  withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfilePath = path.join(
        cfg.modRequest.platformProjectRoot,
        "Podfile"
      );
      let contents = fs.readFileSync(podfilePath, "utf8");

      if (contents.includes(MARKER)) {
        return cfg; // already applied
      }
      if (!contents.includes(ANCHOR)) {
        throw new Error(
          `[withFmtXcode26Fix] Could not find "${ANCHOR}" in the generated Podfile; ` +
            `the plugin needs updating for this React Native / Expo version.`
        );
      }

      contents = contents.replace(ANCHOR, `${ANCHOR}\n${RUBY_SNIPPET}`);
      fs.writeFileSync(podfilePath, contents);
      return cfg;
    },
  ]);

module.exports = withFmtXcode26Fix;
